.gitignore, Gemfile, Rakefile, lib/syntax_error_search.rb, lib/syntax_error_search/code_block.rb, lib/syntax_error_search/code_frontier.rb, lib/syntax_error_search/code_line.rb, lib/syntax_error_search/code_search.rb, lib/syntax_error_search/display_invalid_blocks.rb, lib/syntax_error_search/version.rb, spec/spec_helper.rb, spec/syntax_error_search_spec.rb, spec/unit/code_block_spec.rb, spec/unit/code_frontier_spec.rb, spec/unit/code_line_spec.rb, spec/unit/code_search_spec.rb, spec/unit/display_invalid_blocks_spec.rb, syntax_error_search.gemspec
Many updates here, but the biggest win is that a search can now be recorded so after the fact an observer can replay the logic to look for bugs or optimizations.
=> Record search

CHANGELOG.md, lib/syntax_search.rb, lib/syntax_search/display_invalid_blocks.rb, spec/unit/display_invalid_blocks_spec.rb, spec/unit/exe_spec.rb, spec/unit/syntax_search_spec.rb
As mentioned in https://github.com/zombocom/syntax_search/pull/8#issuecomment-725527786 there are two types of syntax errors that can be hit involving an end:
- It's got and end but wasn't expecting one (unmatched end)
- It needs an end but doesn't have one (missing end)
To make this more clear, the output of SyntaxSearch now specializes for these two cases and gives a helpful output with more context.
=> More specific error messages

CHANGELOG.md, lib/syntax_search/display_invalid_blocks.rb, spec/unit/code_search_spec.rb, spec/unit/display_invalid_blocks_spec.rb
When copying and pasting the output to GitHub issues I found that I could not put it inside of code blocks since the output itself has code blocks. To alleviate this we can use indentation to mark the code block instead. This allows us to directly copy and paste the output into GitHub.
=> Use indentation code blocks instead of code fences

Gemfile, Gemfile.lock, lib/syntax_search.rb, lib/syntax_search/around_block_scan.rb, lib/syntax_search/block_expand.rb, lib/syntax_search/code_block.rb, lib/syntax_search/code_frontier.rb, lib/syntax_search/code_search.rb, lib/syntax_search/display_invalid_blocks.rb, lib/syntax_search/parse_blocks_from_indent_line.rb, spec/unit/around_block_scan_spec.rb, spec/unit/block_expand_spec.rb, spec/unit/code_block_spec.rb, spec/unit/code_frontier_spec.rb, spec/unit/code_search_spec.rb, spec/unit/display_invalid_blocks_spec.rb
To be able to have CodeBlock class not depend on knowledge of all code lines, we need to move the code expansion logic outside of the code class.
It's now being represented in the BlockExpand class which can be independently tested. To simplify writing this class, a helper class AroundBlockScan was introduced. This class automates some of the chores around searching before/after a given block.
The IndentScan class has been renamed to ParseBlocksFromIndentLine to be a little more descriptive about it's purpose and goal, but I'm still struggling to name it.
=> [changelog skip] Refactor: Immutable CodeBlocks

CHANGELOG.md, Gemfile.lock, lib/syntax_search.rb, lib/syntax_search/version.rb, lib/syntax_search/who_dis_syntax_error.rb, spec/unit/who_dis_syntax_error_spec.rb, syntax_search.gemspec
Ripper is the built in parsing library from Ruby. It is much faster than Parser and it has everything we need.
This PR replaces the parser gem with ripper.
=> [close #16] Replace Parser with Ripper

CHANGELOG.md, lib/syntax_search.rb, lib/syntax_search/code_block.rb, lib/syntax_search/code_search.rb, lib/syntax_search/display_invalid_blocks.rb, lib/syntax_search/heredoc_block_parse.rb, spec/fixtures/rexe.rb, spec/unit/exe_spec.rb, spec/unit/heredoc_block_parse_spec.rb
Heredocs in ruby are common sources of indentation even though they cannot cause either an "unmatched" or "unexpected" end syntax errors. To help avoid these false positives when parsing source, we first find and parse all heredocs. If the lines that contain the heredocs are valid, they'll be commented-out/hidden early on. This drastically decreases the chance that heredoc based indentation will lead to false positives.
=> Strip HEREDOC

CHANGELOG.md, exe/syntax_search, lib/syntax_search/around_block_scan.rb, lib/syntax_search/block_expand.rb, lib/syntax_search/code_line.rb, lib/syntax_search/code_search.rb, spec/spec_helper.rb, spec/unit/around_block_scan_spec.rb, spec/unit/code_line_spec.rb, spec/unit/code_search_spec.rb, spec/unit/exe_spec.rb
CodeLines are now lexically aware of keywords. This is used by the AroundBlockScan to allow stopping after a keyword has been hit.
In addition to stripping heredocs before searching, the CodeSearch now also strips lines that contain only comments. The combination of stripping heredocs and comments prevents false positives from lexing individual lines (since a comment might contain valid code i.e. `# def foo; end`. 
New APIs:
- CodeLine#is_comment?
- CodeLine#is_kw?
- CodeLine#is_end?
- AroundBlockScan.stop_after_kw
- AroundBlockScan.scan_neighbors
=> [Close #22] Lines are lexically aware of keywords

CHANGELOG.md, lib/syntax_search/around_block_scan.rb, lib/syntax_search/block_expand.rb, lib/syntax_search/capture_code_context.rb, lib/syntax_search/code_block.rb, lib/syntax_search/code_line.rb, lib/syntax_search/code_search.rb, lib/syntax_search/display_code_with_line_numbers.rb, lib/syntax_search/display_invalid_blocks.rb, spec/unit/code_search_spec.rb, spec/unit/display_invalid_blocks_spec.rb, spec/unit/exe_spec.rb
This change reduces the output to only the minimal context needed.
=> [close #20] Simplify large file output

.gitignore, CHANGELOG.md, lib/syntax_search.rb, lib/syntax_search/code_line.rb, lib/syntax_search/code_search.rb, lib/syntax_search/display_code_with_line_numbers.rb, lib/syntax_search/trailing_slash_join.rb, spec/unit/code_line_spec.rb, spec/unit/code_search_spec.rb, spec/unit/trailing_slash_join_spec.rb
Ruby lines that end with a slash `\` indicate that the next line should be concatenated with the current line so:
```ruby
if "trailing" \
"line" do
end
```
Is functionally equivalent to:
```ruby
if "trailing" "line" do
endf
```
We can replicate this logic by taking note when a line ends with a trailing slash and then concatenating it with the next line.
Functionally the TrailingSlashJoin class does this by concatenating the lines, and then hiding the original line.
To allow for output, the DisplayCodeWithLineNumbers is now aware that a code line may contain multiple code lines, and it will split and render each.
=> [Close #21] Concat lines with trailing slash

CHANGELOG.md, lib/syntax_search.rb, lib/syntax_search/display_invalid_blocks.rb, lib/syntax_search/who_dis_syntax_error.rb, spec/unit/code_search_spec.rb, spec/unit/display_invalid_blocks_spec.rb, spec/unit/who_dis_syntax_error_spec.rb
SyntaxSearch works for other missing keywords other than `end` that would otherwise trigger an `unexpected end` error. This commit adds more explicit banners for these cases.
https://github.com/zombocom/syntax_search/issues/18
=> Banner for different syntax error types

CHANGELOG.md, spec/fixtures/routes.txt.rb, spec/perf/perf_spec.rb, spec/unit/code_search_spec.rb
Makes test cases use foobar style
=> Foobarified some of the test cases

CHANGELOG.md, lib/dead_end/code_block.rb, lib/dead_end/code_frontier.rb, lib/dead_end/code_line.rb, lib/dead_end/code_search.rb, spec/unit/code_line_spec.rb, spec/unit/code_search_spec.rb
Previously we were keeping track of the lines that were not in the frontier via an @indent_hash with the keys as indentation and value as an array.
This was inefficient and caused us to constantly be sorting the keys. Instead, we can get the same information by only sorting once.
As a bonus perf optimization, CodeLine#indent_index generates a key for stable sort and memoizes it so it only has to be allocated once per line.
=> More efficient frontier unvisited line structure

lib/dead_end/around_block_scan.rb, spec/unit/around_block_scan_spec.rb
https://twitter.com/schneems/status/1343598395923996672
=> [changelog skip] Fix comparison of Integer with nil failed

CHANGELOG.md, lib/dead_end/code_line.rb, lib/dead_end/lex_all.rb, spec/unit/capture_code_context_spec.rb, spec/unit/code_line_spec.rb, spec/unit/lex_all_spec.rb
When a line definition ends in if/unless then it does not need an accompanying "end" this can be detected when lexing: https://github.com/ruby/ruby/blob/06b44f819eb7b5ede1ff69cecb25682b56a1d60c/lib/irb/ruby-lex.rb#L374-L375
=> [close #36]Don't count trailing if/unless as a keyword

CHANGELOG.md, README.md, lib/dead_end/auto.rb, lib/dead_end/code_line.rb, spec/integration/ruby_command_line_spec.rb
When a NoMethodError is raised in a non-production environment, instead of producing:
```
scratch.rb:7:in `call': undefined method `upcase' for nil:NilClass (NoMethodError)
```
Ruby programs with `dead_end` required will produce:
```
scratch.rb:7:in `call': undefined method `upcase' for nil:NilClass (NoMethodError)
1  class Pet
6    def call
❯ 7      puts "Come here #{@neam.upcase}"
8    end
9  end
```
This behavior is disabled in "production" environments as it requires reading from disk and parsing. The main behavior of DeadEnd is reasonably production safe as syntax errors stop a program from executing further and are limited to the number of files on disk. A NoMethodError in production is likely to be hit repeatedly.
=> [close #42] Annotate NoMethodError

CHANGELOG.md, lib/dead_end/auto.rb, spec/integration/ruby_command_line_spec.rb
Previously when a NoMethodError was raised from within the DeadEnd monkeypatch then an infinite loop would be caused by calling `e.message` since that would trigger our monkeypatch recursively.
This patch fixes the issue by aliasing the original method and explicitly using that instead. 
This behavior is also tested. So while there still might be internal errors, at least they won't result in infinite loops with no output.
=> Safer NoMethodError annotation

CHANGELOG.md, Gemfile.lock, lib/dead_end/auto.rb, lib/dead_end/version.rb, spec/integration/ruby_command_line_spec.rb
There's a conflict when another gem has a monekypatch method named `original_require`. By adding a namespace we should ensure that there no conflict.
=> Namespace method aliases

CHANGELOG.md, dead_end.gemspec
Hey @schneems,
I noticed the gem includes the demo gif, which increases the gem size by ~50 kb. This change makes it so future versions avoid including files under that directory.
=> Do not include demo gif in the built gem

lib/dead_end/display_invalid_blocks.rb, lib/dead_end/who_dis_syntax_error.rb, spec/unit/display_invalid_blocks_spec.rb
Adds a missing backtick on `unknown` in the invalid block banner.
=> [changelog skip] Added missing backtick on 'unmatched unknown detected'

CHANGELOG.md, lib/dead_end/who_dis_syntax_error.rb, spec/unit/who_dis_syntax_error_spec.rb
If a Ruby stacktrace includes two syntax errors, like below:
```
➜  dead_end git:(main) ✗ ruby dog.rb
dog.rb:5: syntax error, unexpected `end', expecting ']'
end
dog.rb:10: syntax error, unexpected end-of-input, expecting `end'
```
We should parse only the first time we encounter errors, and not the second
time. If we know the type of error and unmatched symbol, we shouldn't need to
check those again.
=> Parse error once and not twice if there's more than one available

CHANGELOG.md, lib/dead_end/who_dis_syntax_error.rb, spec/unit/who_dis_syntax_error_spec.rb
Consider `tIDENTIFIER` in Ruby 2.6 and `local variable or method` in Ruby 2.7 and 3.0
`dead_end` was showing just the syntax error, but not the banner: 
```
➜   dead_end datadog.rb
file: /Users/mauro-oto/Projects/dead_end/datadog.rb
simplified:
4  Datadog.configure do |c|
❯  5    ["rails", "grpc"].each do |service
❯ 11    end
12  end
```
With the fix:
```
➜  dead_end datadog.rb
DeadEnd: Unmatched `|` character detected
Example:
`do |x` should be `do |x|`
file: /Users/mauro-oto/Projects/dead_end/datadog.rb
simplified:
4  Datadog.configure do |c|
❯  5    ["rails", "grpc"].each do |service
❯ 11    end
12  end
```
=> Consider if syntax error caused an unexpected variable instead of end

CHANGELOG.md, lib/dead_end/capture_code_context.rb, spec/fixtures/derailed_require_tree.rb.txt, spec/integration/improvement_regression_spec.rb, spec/unit/capture_code_context_spec.rb
Described in https://github.com/zombocom/dead_end/issues/32 we are capturing the correct code blocks, however if the problem is mis-matched keyword, then the internals of the block are incorrectly hidden.
Code was added to work backwards and show that extra mis-matched keyword, unfortunately it grabbed more and caused a less-than-ideal output:
Before:
```
$ dead_end spec/fixtures/derailed_require_tree.rb.txt
DeadEnd: Missing `end` detected
This code has a missing `end`. Ensure that all
syntax keywords (`def`, `do`, etc.) have a matching `end`.
file: /Users/rschneeman/Documents/projects/dead_end/spec/fixtures/derailed_require_tree.rb.txt
simplified:
5  module DerailedBenchmarks
6    class RequireTree
7      REQUIRED_BY = {}
9      attr_reader   :name
10      attr_writer   :cost
11 …
```
=> [close #50] Less greedy unmatched kw capture

CHANGELOG.md, lib/dead_end/code_line.rb, spec/unit/code_line_spec.rb
When there is an "endless" method definition, we don't want to count it as having a keyword, otherwise when we try to expand it will search for a matching `end` an possibly introduce a problem in the search.
To detect this case I use the same logic introduced in https://github.com/ruby/irb/commit/826ae909c9c93a2ddca6f9cfcd9c94dbf53d44ab
For reference here are lex of a regular method definition (first line only) and then an "endless" definition:
```
irb(main):015:0> Ripper.lex("def square(x)")
=>
[[[1, 0], :on_kw, "def", FNAME],
[[1, 3], :on_sp, " ", FNAME],
[[1, 4], :on_ident, "square", ENDFN],
[[1, 10], :on_lparen, "(", BEG|LABEL],
[[1, 11], :on_ident, "x", ARG],
[[1, 12], :on_rparen, ")", ENDFN]]
irb(main):016:0> Ripper.lex("def square(x) = x * x")
=>
[[[1, 0], :on_kw, "def", FNAME], …
```
=> [close #75] Support endless method definition

CHANGELOG.md, exe/dead_end, lib/dead_end/display_invalid_blocks.rb, spec/integration/exe_cli_spec.rb, spec/spec_helper.rb
Mirroring the behavior from `ruby -wc` the command line now returns non-zero exit codes when it finds a syntax error:
```
$ ruby -wc /tmp/scratch.rb
/tmp/scratch.rb:3: syntax error, unexpected `end', expecting ']'
$ echo $?
1
```
New behavior:
```
$ ./exe/dead_end /tmp/scratch.rb
DeadEnd: Unmatched `]` detected
file: /tmp/scratch.rb
simplified:
1  def foo
❯ 2    foo = [ 1,1,1
3  end
$ echo $?
1
```
The alternative to this logic would be to return 0 for all cases unless an internal error happens. 
This change will allow the vscode extension to use an exit code rather than relying on output strings https://github.com/zombocom/dead_end-vscode/blob/2f2560a073c93015e05d0baab0bf5e2853866e0f/extension.js#L16.
=> Return non-zero status code on exceptions found

CHANGELOG.md, README.md, lib/dead_end.rb, lib/dead_end/code_block.rb, lib/dead_end/code_frontier.rb, lib/dead_end/display_invalid_blocks.rb, lib/dead_end/explain_syntax.rb, lib/dead_end/left_right_lex_count.rb, spec/fixtures/ruby_buildpack.rb.txt, spec/integration/dead_end_spec.rb, spec/integration/exe_cli_spec.rb, spec/integration/improvement_regression_spec.rb, spec/spec_helper.rb, spec/unit/dead_end_spec.rb, spec/unit/explain_syntax_spec.rb
As described in https://github.com/zombocom/dead_end/issues/68#issuecomment-955575369. This implements a method of checking the source code for logically missing component pairs:
- {}
- []
- |<value>|
- ()
- keyword/end
It seems to be much more robust than using a regex on the parser errors. It also seems to provide more confident results than the parser errors.
Here's example output:
```
$ DEBUG_DISPLAY=1 be rspec spec/integration/ --format=f
Unmatched keyword, missing `end' ?
1  Rails.application.routes.draw do
❯ 113    namespace :admin do
❯ 116    match "/foobar(*path)", via: :all, to: redirect { |_params, req|
❯ 120    }
121  end
syntax error, unexpected ':', expecting end-of-input
1  describe "webmock tests" do
22    it "body" do
27      query = Cutlass::FunctionQuery.new(
❯ 28 …
```
=> Add lex based banner

CHANGELOG.md, lib/dead_end/auto.rb, spec/integration/ruby_command_line_spec.rb
When we proxy `Object.load` to `Kernel.load` we were firing `DeadEnd.handle_error` twice. Switching the test over to a `load` instead of a `require_relative` makes the error show up, which can then be asserted via adding the `once` call in rspec.
I still don't know why this code was needed in the first place.
close #97
=> Fix double output

lib/dead_end/explain_syntax.rb
I don't believe you can make a syntax error by missing a `#{` in a string, if you do then you end up with no string embed:
```
"foo}" # => No syntax error
"#foo}" # => No syntax error
"{foo}" # => No syntax error
```
Removing this suggestion makes the error more clear. The default message will still be used which is essentially the same message minus the `#{` part.
=> Remove string embed suggestion

lib/dead_end.rb, lib/dead_end/code_frontier.rb, lib/dead_end/insertion_sort.rb, spec/unit/insertion_sort_spec.rb
Before:  0.230749   0.005489   0.236238 (  0.237043)
After:  0.197075   0.005009   0.202084 (  0.202950)
To generate profiler output, run:
```
$ DEBUG_PERF=1 bundle exec rspec spec/integration/dead_end_spec.rb
```
See the readme for more details. You can do that against the commit before this one, and this one to see the difference.
Using `qcachegrind` on Mac, generating an output with `RubyProf::CallTreePrinter` I saw:
That a lot of time was being spent in `CodeFrontier#<<`, specifically in the `sort!` function and `CodeBlock<=>`.
Because we control insertion into the array, we know that it is always sorted. We can leverage this info to place new elements in at the right location instead of placing them and then re-sorting the whole array just to place one element.
I experimented with …
=> ~1.15x faster perf w/ CodeFrontier insertion sort

CHANGELOG.md, lib/dead_end/cli.rb, spec/unit/cli_spec.rb
The DeadEnd vscode extension relies on calling `dead_end --terminal <filename>` which was previously possible because calling `OptionParser#parse` mutates ARGV. The filename should be the first argument, but only after parsing, not before.
=> Fix CLI edge case around position of arguments

lib/dead_end/clean_document.rb, spec/unit/clean_document_spec.rb
Benchmarking with `ruby_buildpack.rb.txt`:
Before:   0.195756   0.005201   0.200957 (  0.202021)
After:   0.148460   0.003634   0.152094 (  0.152692)
To generate profiler output, run:
```
$ DEBUG_PERF=1 bundle exec rspec spec/integration/dead_end_spec.rb
```
See the readme for more details. You can do that against the commit before this one and this one to see the difference.
Before sha: 58a8d74aff54a311f0f2b5484ff64b6a5338eca2
After sha: 0b4daca74fab5dc2979813461c0f2649951185e5
I was using ruby prof to try to find perf opportunities when I saw this output from the `CallStackPrinter`:
I noticed a lot of time spent in `CleanDocument`, which was curious as it's an N=1 process that happens before we do any looping or iteration.
I also saw output from the `RubyProf::GraphHtmlPrinter` that we …
=> ~1.32x Faster checking with CleanDocument regex

CHANGELOG.md, CODE_OF_CONDUCT.md, README.md
Links on README were not completely dead as they were redirecting to the right
place, but this fixes them. Also fixing links on the code of conduct, as it
seems to bring up the italian version for some reason instead of the english
version.
=> Update links on readme and code of conduct

lib/dead_end/code_frontier.rb
Identified in the profiler as taking a long time
Before:     
By removing the `Array#-` call we speed that section up by roughly double
After: 
Before:   0.163143   0.004160   0.167303 (  0.167356)
After:    0.135444   0.003195   0.138639 (  0.138698)
=> Faster unvisited_lines removal

lib/dead_end/clean_document.rb, lib/dead_end/code_line.rb, lib/dead_end/lex_all.rb, lib/dead_end/lex_value.rb
Several PRs aimed at increasing performance.
Main:   0.160596   0.004052   0.164648 (  0.165109)
This branch:   0.113262   0.002467   0.115729 (  0.115816)
=> Miscelaneous perf commits

CHANGELOG.md, lib/dead_end.rb, lib/dead_end/pathname_from_message.rb, spec/unit/pathname_from_message_spec.rb
Previously I made the assumption that the filename would be the first part of the error message for a syntax error before the colon `:` while this is false, it is especially false on windows where every path starts with a drive letter and a colon such as `c://hello/world.rb`.
This commit fixes that problem by checking for the file on disk and appending more parts to the string.
This is not foolproof because an error message might be possible that someone is using a colon with a file that actually exists in front of it like:
```
/lol/foo.rb:imactuallyadirectory/realfile.rb
```
In this case if `/lol/foo.rb` existed then it would quit looking.
While I'm noting this edge case for completeness, I am not currently handling it. I think case that would be rare. 
When SyntaxError is refactored in …
=> Fix windows compatibility

CHANGELOG.md, lib/dead_end/left_right_lex_count.rb, spec/unit/explain_syntax_spec.rb
When performing a performance test on https://github.com/kddnewton/syntax_tree/blob/50f9fc1b815156bdde53f13d4f250d9522f15e64/test/syntax_tree_test.rb I noticed a strange output. The explain syntax indicated that it was missing a bracket when I had only deleted an `end`: 
```
$ time DEAD_END_TIMEOUT=10 ./exe/dead_end spec/fixtures/syntax_tree.rb.txt
--> /Users/rschneeman/Documents/projects/dead_end/spec/fixtures/syntax_tree.rb.txt
Unmatched `]', missing `[' ?
Unmatched keyword, missing `end' ?
6  class SyntaxTree < Ripper
170    def self.parse(source)
174    end
176    private
❯  754    def on_args_add(arguments, argument)
❯  776    class ArgsAddBlock
❯  810    end
9233  end
DEAD_END_TIMEOUT=10 ./exe/dead_end spec/fixtures/syntax_tree.rb.txt  1.63s user 0.07s system 99% cpu 1.703 total
``` …
=> Handle shorthand syntax in explanations

CHANGELOG.md, lib/dead_end/ripper_errors.rb, spec/unit/explain_syntax_spec.rb
While investigating https://github.com/zombocom/dead_end/pull/116 I realized that the shorthand syntax does not have to be limited to our existing "pairs" characters that we already track. While coming up with additional test cases I realized that the existing `on_parse_error` does not emit an error for the code: `%Q* lol` (missing a `*` to close the string).
This commit adds the missing check (coming from `compile_error`) as well as several others coming from the event table:
```
irb(main):008:0> Ripper::PARSER_EVENT_TABLE.select {|(k,v)| k.to_s.end_with?("error") }.keys
=> [:alias_error, :assign_error, :class_name_error, :param_error, :irb(main):008:0> Ripper::PARSER_EVENT_TABLE.select {|(k,v)| k.to_s.end_with?("error") }.keys
=> [:alias_error, :assign_error, :class_name_error, …
```
=> Handle more ripper errors

.circleci/config.yml, CHANGELOG.md, lib/dead_end/core_ext.rb, spec/integration/ruby_command_line_spec.rb
The `require_relative` method is different from other monkey patches because the code uses the caller location to change behavior. That means if you monkey patch that method and alias it back to the original `require_relative` it will not work as expected. Here is the c-code for `require_relative` https://github.com/ruby/ruby/blob/b35b7a1ef25347735a6bb7c28ab7e77afea1d856/load.c#L907-L924. 
The way that bootsnap (and others) work around this limitation is by grabbing the second to last caller location and requiring relative to that file instead. This method uses the `Thread::Backtrace::Location` class:
```
caller_locations(1..1).first.class
=> Thread::Backtrace::Location
```
This change in ruby https://github.com/ruby/ruby/pull/4519 changed the behavior of that class when being returned …
=> Support Ruby 3.1

CHANGELOG.md, Gemfile.lock, lib/dead_end/lex_all.rb, lib/dead_end/lex_value.rb, lib/dead_end/version.rb, spec/unit/code_line_spec.rb
For some weird reason this line is detected as a keyword line:
```
type: :module,
```
Though it clearly isn't. Ripper:
```
require 'ripper'
pp Ripper.lex(<<~'EOM')
{
type: :module,
}
EOM
```
Produces:
```
[[[1, 0], :on_lbrace, "{", BEG|LABEL],
[[1, 1], :on_ignored_nl, "\n", BEG|LABEL],
[[2, 0], :on_sp, "  ", BEG|LABEL],
[[2, 2], :on_label, "type:", ARG|LABELED],
[[2, 7], :on_sp, " ", ARG|LABELED],
[[2, 8], :on_symbeg, ":", FNAME],
[[2, 9], :on_kw, "module", ENDFN],
[[2, 15], :on_comma, ",", BEG|LABEL],
[[2, 16], :on_ignored_nl, "\n", BEG|LABEL],
[[3, 0], :on_rbrace, "}", END],
[[3, 1], :on_nl, "\n", BEG],
[[4, 0], :on_const, "EOM", CMDARG]]
```
This is the problem line:
```
[[2, 9], :on_kw, "module", ENDFN],
```
Digging into the IRB source code they handled this case here …
=> Fix incorrect keyword lexing

spec/fixtures/syntax_tree.rb.txt, spec/integration/dead_end_spec.rb, spec/spec_helper.rb
This file is 9k lines long and even with the currently optimized algorithm takes about 1.6s to search. The goal is to find a way to get it under 1 second.
If someone is working with such large files they can set their DEAD_END_TIMEOUT=2 and be perfectly fine, but perf improvements that would allow this file to parse under 1 second would hopefully also speed up other cases.
=> Failing test for aspirational perf improvements

lib/dead_end/code_search.rb, lib/dead_end/parse_blocks_from_indent_line.rb
While adding new lines we can first check if ALL of them are valid. If so we can skip repeatedly calling ripper to check `CodeBlock#valid?`
Before: Finished in 1.43 seconds (files took 0.14836 seconds to load)
After:  Finished in 1.17 seconds (files took 0.15893 seconds to load)
=> 1.22x faster Greedy new lines

CHANGELOG.md, lib/dead_end/around_block_scan.rb, lib/dead_end/block_expand.rb, spec/integration/dead_end_spec.rb, spec/unit/around_block_scan_spec.rb, spec/unit/capture_code_context_spec.rb
Previously we were accidentally not using the persisted @before_index and instead using the "original" before index. This commit fixes that problem and adds a test for the behavior.
=> Fix AroundBlockScan

spec/integration/dead_end_spec.rb, spec/unit/capture_code_context_spec.rb, spec/unit/code_search_spec.rb
The "capture code context spec" currently depends on code search which can change as the algorithm evolves. This makes development hard since it's unclear when those tests fail if it's because the functionality changed or the search output changed. Also since the existing "capture context" logic is based on quirks of how the code search algorithm works, when the search is improved it may need different "capture context" logic before it produces good output.
For these cases, we actually need to duplicate the tests 3 times.
- Integration with everything
- Capture Code Context works with static input
- CodeSearch produces the static input we expect
So when all 3 start failing then we can look at it in isolation and see if it "makes sense". I.e. if the CodeSearch output actually "improved" …
=> Decouple Capture Context tests

dead_end.gemspec
When vendoring a default gem in the Ruby repository it uses a different path structure:
```
$ tool/sync_default_gems.rb dead_end
Sync zombocom/dead_end 
```
This causes an error in the gemspec when trying to require a relative file. To overcome this error, other default gems will try to require the expected location and then fallback to a different path such as https://github.com/ruby/error_highlight/blob/f88b6fab2ff34559a0f08d019d574dbb52426a20/error_highlight.gemspec#L4-L8
=> Fix default gem require error

CHANGELOG.md, lib/dead_end/core_ext.rb, spec/integration/ruby_command_line_spec.rb
Currently dead_end works by monkey patching require. This causes confusion and problems as other tools are not expecting this. For example https://github.com/zombocom/derailed_benchmarks/issues/204 and https://github.com/zombocom/dead_end/issues/124. This PR utilizes the new SyntaxError#detailed_message as introduced in https://github.com/ruby/ruby/pull/5516 that will be released in Ruby 3.2.
That means that developers using dead_end with Ruby 3.2+ will experience more consistent behavior.
As pointed out in #31 the current version of dead_end only works if the developer requires dead_end and then invokes `require`.
This behavior is still not fixed for Ruby 3.2+ 
```
$ ruby -v
ruby 3.2.0preview1 (2022-04-03 master f801386f0c) [x86_64-darwin20]
$ cat monkeypatch.rb
SyntaxError.prepend …
```
=> Annotate syntax error without require

CHANGELOG.md, dead_end.gemspec, exe/dead_end, lib/dead_end.rb, lib/dead_end/api.rb, lib/dead_end/core_ext.rb, lib/dead_end/version.rb, spec/integration/ruby_command_line_spec.rb, spec/spec_helper.rb
Instead of having to load all dead end code on every invocation of Ruby, we can delay requiring the files until they're actually needed (on SyntaxError).
Resolves this comment https://github.com/ruby/ruby/pull/5859#pullrequestreview-976985456
This requirement makes the library a little unusual in that `dead_end/version` no longer defines `DeadEnd::VERSION` but rather a placeholder value in another constant so the gem isn't eagerly loaded when using the project's gemspec in local tests.
=> Lazyload DeadEnd internals on syntax error

.circleci/config.yml, lib/dead_end/core_ext.rb
For some reason yjit tests on ruby/ruby are failing against the current code:
```
$ time RUBY_YJIT_ENABLE=1 RUBY_TESTOPS="-q --tty=no" make -s check RUN_OPTS=""
```
While this works without yjit enabled it seems the problem is related to an error happening within the `SyntaxError#detailed_message`. It also seems that the other part of the equation is `autoload` with a gem on disk (instead of something in the stdlib). 
One immediate fix is to ensure that if there are any internal errors, that the original syntax error always takes precedent. I've tried to reproduce the failure removing dead_end but I'm unable to, so I want to move ahead. If we find dead_end does not work with YJIT in cases in the future then the YJIT team (and I) can investigate.
=> Fix yjit support

CHANGELOG.md, lib/dead_end/core_ext.rb, spec/unit/api_spec.rb
The kwarg `highlight` is intended to enable/disable control characters https://twitter.com/schneems/status/1532693550474924032. This change brings DeadEnd into alignment with error_highlight with the ability to turn on/off the control characters at will.
One downside of this implementation is that for the case where highlighting is enabled I'm calling super twice. This might have performance implications if someone else is overwriting SyntaxError and doing something possibly expensive (much like DeadEnd is doing).
Alternatively we could try to detect or strip the control code. This would be harder and possibly error prone.
Also addresses:
- Disable/enable dead end based on kwarg https://github.com/ruby/ruby/pull/5516/files#diff-f2e6c18de8171e389aeff0b8d25b2755253108a59a13baf7167c2ffa0af36a …
=> Respect SyntaxError#detailed_message `highlight` kwarg

CHANGELOG.md, dead_end.gemspec, lib/dead_end/api.rb, lib/dead_end/core_ext.rb, lib/dead_end/version.rb, spec/integration/ruby_command_line_spec.rb
As pointed out in https://github.com/ruby/ruby/pull/5859#pullrequestreview-994422579 the DeadEnd constant will already be loaded when used as a default gem.
This change moves lazy loading from `autoload` into manually requiring the `dead_end/api` right before we need it. This breaks the API I defined in 4.0 that said we would autoload based on DeadEnd constant access, while I extremely doubt anyone is dependent on that yet it's not hard to rev another major version. I want to be clear and cautious about breaking changes. 
This is a nice change in that the tests got a little simpler and I'm not doing anything strange like having to define an Unloaded constant to not trigger the autoload. An alternative would be to introduce a `DeadEnd::Api` and only have two methods on it `call` and …
=> Fix lazy load for default gem

CHANGELOG.md, spec/integration/exe_cli_spec.rb, spec/integration/ruby_command_line_spec.rb, spec/spec_helper.rb, spec/unit/api_spec.rb
I added `test-syntax-suggest` for `ruby/ruby` CI at https://github.com/ruby/ruby/pull/6287
We need to some of workarounds about `syntax_suggest`.
=> Backport workaround for running on ruby/ruby repo

CHANGELOG.md, lib/syntax_suggest/cli.rb, lib/syntax_suggest/display_invalid_blocks.rb, spec/integration/ruby_command_line_spec.rb, spec/unit/api_spec.rb, spec/unit/display_invalid_blocks_spec.rb
Due to a problem with ripper we do not recognize `break` as invalid code. It's confusing that "Syntax OK" is output in that case.
When there's no syntax error, the algorithm should not say anything. The exception is in the CLI and that's for compatibility with `ruby -wc`
```
$ cat /tmp/break.rb
break
⛄️ 3.1.2 🚀 /Users/rschneeman/Documents/projects/syntax_suggest (schneems/no-syntax-not-okay-break)
$ ruby -wc /tmp/break.rb
Syntax OK
```
> Note that this is invalid, running this code will raise a Syntax error.
```
$ exe/syntax_suggest /tmp/break.rb
Syntax OK
```
Close #157
=> Do not output "Syntax OK" when there's an error

CHANGELOG.md, Gemfile.lock, README.md, lib/syntax_suggest/capture_code_context.rb, lib/syntax_suggest/cli.rb, lib/syntax_suggest/display_code_with_line_numbers.rb, lib/syntax_suggest/version.rb, spec/integration/ruby_command_line_spec.rb, spec/integration/syntax_suggest_spec.rb, spec/unit/clean_document_spec.rb, spec/unit/cli_spec.rb, spec/unit/code_search_spec.rb, spec/unit/display_invalid_blocks_spec.rb
There was a report where the unicode character `"\u276F"` i.e. `❯` would not render on some older fonts. To improve compatibility, we are switching to the standard right angle bracket `>`.
=> Replace unicode arrow with right angle bracket

CHANGELOG.md, lib/syntax_suggest/core_ext.rb
Original:
```
https://bugs.ruby-lang.org/issues/19138
Co-authored-by: Nobuyoshi Nakada [nobu@ruby-lang.org](mailto:nobu@ruby-lang.org)
```
Added: 
- Support for current releases of 3.2.0-preview
- Changelog
=> Build on #163: No longer need PathnameFromMessage with SyntaxError#path

lib/syntax_suggest/core_ext.rb
https://bugs.ruby-lang.org/issues/19138
Co-authored-by: Nobuyoshi Nakada <nobu@ruby-lang.org>
=> No longer need PathnameFromMessage with SyntaxError#path.

.github/workflows/ci.yml, CHANGELOG.md, lib/syntax_suggest/core_ext.rb, spec/integration/ruby_command_line_spec.rb, spec/unit/api_spec.rb
Ruby 3.2.0rc1 introduced SyntaxError#path in addition to the ability to monkey patch SyntaxError. That means all code inside of this syntax error is guaranteed to be on Ruby 3.2. As the contents of the preview release were unstable, we do not have to continue to support older preview releases that did not contain SyntaxError#path
=> Drop support for old 3.2.0 preview versions

spec/integration/ruby_command_line_spec.rb
It's resolved by https://github.com/ruby/ruby/commit/5bb43aeb890657ea586e3fabbf763e5b5670ffd7
=> Removed the needless test guard for syntax_suggest.

.github/workflows/ci.yml, CHANGELOG.md
Fix CI failures with 3.2.0-rc1.
=> Use the released ruby 3.2

spec/integration/exe_cli_spec.rb
Running the file with shebang has a few issues.
* shebang is an OS dependent feature. Many modern UNIX-like OSes support it, but not all, e.g., Windows.
* `env` command may not be in `/usr/bin`.
* "ruby" command may not be "ruby", when `--program-suffix` or other configuration option is used.
=> Run with the given ruby command

CHANGELOG.md, lib/syntax_suggest/core_ext.rb
Fix https://bugs.ruby-lang.org/issues/19285
In particular, the part  hidden from RDoc by this PR is not used in the versions syntax_suggest bundled with.
=> Hide internal document and detail of `Kernel` monkey patching

.rspec
It is enabled automatically if possible.
Forcing this option makes https://github.com/rspec/rspec-core/pull/3017 useless.
=> Remove unnecessary `--color` option

.github/workflows/ci.yml, README.md, bin/rake, bin/rspec
Because `syntax_suggest` is a default gem you can get conflicts when working on this project with Ruby 3.2+. To fix conflicts you can disable loading `syntax_suggest` as a default gem by using then environment variable `RUBYOPT` with the value `--disable=syntax_suggest`. The `RUBYOPT` environment variable works the same as if we had entered those flags directly in the ruby cli (i.e. `ruby --disable=syntax_suggest` is the same as `RUBYOPT="--disable=syntax_suggest" ruby`). It's needed because we don't always directly execute Ruby and RUBYOPT will be picked up when other commands load ruby (`rspec`, `rake`, or `bundle` etc.).
There are some binstubs that already have this done for you. Instead of running `bundle exec rake` you can run `bin/rake`. Binstubs provided:
- `bin/rake`
- …
=> Introduce binstubs to set RUBYOPT for development

lib/syntax_suggest/core_ext.rb
syntax_suggest did not work great when there is no new line at the end of the input file.
Input:
```
def foo
end
end # No newline at end of file
```
Previous output:
```
$ ruby test.rb
test.rb: --> test.rb
Unmatched `end', missing keyword (`do', `def`, `if`, etc.) ?
> 1  def foo
> 2  end
> 3  end # No newline at end of filetest.rb:3: syntax error, unexpected `end' (SyntaxError)
end # No newline at end of file
^~~
```
Note that "test.rb:3: ..." is appended to the last line of the annotation.
This change makes sure that the annotation ends with a new line.
New output:
```
$ ruby test.rb
test.rb: --> test.rb
Unmatched `end', missing keyword (`do', `def`, `if`, etc.) ?
> 1  def foo
> 2  end
> 3  end # No newline at end of file
test.rb:3: syntax error, unexpected `end' (SyntaxError)
end # No …
```
=> The annotation must end with a new line

CHANGELOG.md, lib/syntax_suggest/around_block_scan.rb, lib/syntax_suggest/capture_code_context.rb, spec/integration/syntax_suggest_spec.rb, spec/unit/capture_code_context_spec.rb, spec/unit/display_invalid_blocks_spec.rb
I previously left a comment stating I didn't know why a certain method existed. In investigating the code in `CaptureCodeContext#capture_before_after_kws` I found that it was added as to give a slightly less noisy output.
The docs for AroundBlockScan#capture_neighbor_context only describe keywords as being a primary concern. I modified that code to only include lines that are keywords or ends. This reduces the output noise even more.
This allows me to remove that `start_at_next_line` method.
One weird side effect of the prior logic is it would cause this code to produce this output:
```
class OH
def hello
def hai
end
end
```
```
1  class OH
> 2    def hello
4    def hai
5    end
6  end
```
But this code to produce this output:
```
class OH
def hello
def hai
end
end
```
```
1  class OH
> 2 …
```
=> Clean up output

spec/integration/ruby_command_line_spec.rb, spec/spec_helper.rb
I picked tweak commits from https://github.com/ruby/ruby
=> Backport commits from ruby/ruby

CHANGELOG.md, lib/syntax_suggest/api.rb
The env var DEBUG does not work to produce detailed output. It is SYNTAX_SUGGEST_DEBUG. It was changed as part of the dead_end to syntax_suggest migration for Ruby 3.2
=> Fix warning message

syntax_suggest.gemspec
`spec.files.grep(%r{^exe/}) { |f| File.basename(f) }` is not working with `ruby/ruby` repo. Therefore, https://github.com/ruby/ruby/blob/master/libexec/syntax_suggest is not installed with Ruby installation.
I replaced `spec.executables` to simple filename because it's rarely to add new executables.
=> Use hard-coded filename for executables.

CHANGELOG.md, lib/syntax_suggest/pathname_from_message.rb, spec/integration/ruby_command_line_spec.rb, spec/unit/pathname_from_message_spec.rb
See https://bugs.ruby-lang.org/issues/19755
Ref: https://github.com/ruby/ruby/pull/8070
In Ruby 3.3, using `eval` without providing a source location will now default to `"(eval at #{__FILE__}:#{__LINE__})"`.
cc @schneems @nobu @hsbt
=> Handle new eval source location

.github/workflows/ci.yml, CHANGELOG.md, Gemfile, Gemfile.lock, README.md, lib/syntax_suggest/api.rb, lib/syntax_suggest/clean_document.rb, lib/syntax_suggest/code_block.rb, lib/syntax_suggest/code_line.rb, lib/syntax_suggest/explain_syntax.rb, lib/syntax_suggest/lex_all.rb, lib/syntax_suggest/ripper_errors.rb, spec/unit/api_spec.rb, spec/unit/explain_syntax_spec.rb, spec/unit/lex_all_spec.rb
Prism will be the parser in Ruby 3.3. We need to support Ruby 3.0+, so we must "dual boot" both prism and Ripper.
Todo:
=> Add support for the Prism parser

spec/unit/explain_syntax_spec.rb
The original ripper test was very stable as the output didn't change. Prism is under active development and changing their output shouldn't cause a failure to the ruby/ruby test suite like https://github.com/ruby/ruby/actions/runs/7104601478/job/19339940315.
This commit moves from checking exact output to asserting that the string we get back is not empty. This should give the same level of confidence that some error message was caught, and is less brittle.
=> Change assertion to not rely on exact text from prism

lib/syntax_suggest/around_block_scan.rb, lib/syntax_suggest/block_expand.rb, lib/syntax_suggest/capture_code_context.rb, lib/syntax_suggest/parse_blocks_from_indent_line.rb, spec/unit/block_expand_spec.rb, spec/unit/clean_document_spec.rb
I found some of typo by https://github.com/client9/misspell and fixed them.
=> Typofix by misspell

exe/syntax_suggest
Otherwise it makes incorrect assumption about RubyGems layout.
RubyGems always guarantees the gem's `lib` is in $LOAD_PATH.
Follow up of https://github.com/ruby/syntax_suggest/pull/226
=> A gem executable should not use require_relative

.github/dependabot.yml
We should ignore to check changelog for dependabot update.
ref. https://github.com/ruby/syntax_suggest/actions/runs/11554424291/job/32157600639
=> Added 'skip changelog' label for dependabot update

spec/integration/syntax_suggest_spec.rb, spec/spec_helper.rb
from https://bugs.ruby-lang.org/issues/20309
`benchmark` library will be changed bundled gems at Ruby 3.5. We should mark related examples as optional.
=> Make benchmark examples as optional
